# Generated by Django 5.2.1 on 2025-06-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_shoppinglist_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
